In [6]:
import pandas as pd

In [7]:
df = pd.read_csv(
    "../Data/raw_ai_student_impact_dataset (1).csv"
)

df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [8]:
df.info()

df.isnull().sum()

df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  str
 2   Year_of_Study               50000 non-null  str
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  str
 6   Prompt_Engineering_Skill    50000 non-null  str
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  str
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  str
dtypes: bool(1), float64(5), int64(4), str(6)
memory usage: 5.8 MB

np.int64(0)

50k rows 16 Columns
0 empty values
0 duplicated

In [9]:
for col in ["Major_Category", "Year_of_Study", "Primary_Use_Case", "Burnout_Risk_Level"]:
    print("\n", col)
    print(df[col].value_counts())

 Major_Category
Major_Category
STEM          15059
Business      12538
Humanities     9994
Medical        6476
Arts           5933
Name: count, dtype: int64

 Year_of_Study
Year_of_Study
Junior       11045
Freshman     11031
Senior       10634
Sophomore     9860
Graduate      7430
Name: count, dtype: int64

 Primary_Use_Case
Primary_Use_Case
Debugging/Troubleshooting    12295
Copywriting/Drafting         12011
Ideation                     10721
Summarizing_Reading           8633
Direct_Answer_Generation      6340
Name: count, dtype: int64

 Burnout_Risk_Level
Burnout_Risk_Level
Medium    21144
Low       16369
High      12487
Name: count, dtype: int64

In [10]:
df["gpa_change"] = (
    df["Post_Semester_GPA"]
    - df["Pre_Semester_GPA"]
)
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level,gpa_change
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High,-0.025
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low,-0.125
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium,0.101
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium,0.211
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium,0.163

In [ ]:
# GPA CHANGE PER MAJOR
df.groupby(
    "Major_Category"
)["gpa_change"].mean()

Major_Category
Arts          0.196902
Business      0.194325
Humanities    0.197976
Medical       0.201399
STEM          0.217302
Name: gpa_change, dtype: float64

In [ ]:
#* GPA CHANGE PER SUBCRIPTION ( FREE OR PAID )
df.groupby(
    "Paid_Subscription"
)["gpa_change"].mean()

Paid_Subscription
False    0.200429
True     0.206971
Name: gpa_change, dtype: float64

In [ ]:
# Average Gpa change of Students who used ai grouped by how many hours do they use ai at a weekly basis 
df.groupby(
    pd.cut(df["Weekly_GenAI_Hours"], bins=5)
)["gpa_change"].agg(["mean", "count"])

                        mean  count
Weekly_GenAI_Hours
(-0.04, 8.0]        0.202014  30762
(8.0, 16.0]         0.228547  11590
(16.0, 24.0]        0.186611   4488
(24.0, 32.0]        0.162135   1854
(32.0, 40.0]        0.121399   1306

In [30]:
# Retention rate of students based on their use of ai weekly
df.groupby(
    pd.cut(df["Weekly_GenAI_Hours"], bins=5)
)["Skill_Retention_Score"].agg(["mean"],)

                         mean
Weekly_GenAI_Hours
(-0.04, 8.0]        76.240489
(8.0, 16.0]         76.952620
(16.0, 24.0]        75.730285
(24.0, 32.0]        68.668711
(32.0, 40.0]        65.487090

In [31]:
df.groupby(
    pd.cut(df["Anxiety_Level_During_Exams"], bins = 10)
)["Weekly_GenAI_Hours"].agg(["mean", "count"])

                                 mean  count
Anxiety_Level_During_Exams
(0.991, 1.9]                 5.999950   5655
(1.9, 2.8]                   6.523216   5752
(2.8, 3.7]                   7.146960   7806
(3.7, 4.6]                   7.809920   8749
(4.6, 5.5]                   8.402976   8222
(5.5, 6.4]                   9.280824   6107
(6.4, 7.3]                  11.118216   3850
(7.3, 8.2]                  12.438616   2088
(8.2, 9.1]                  14.888436   1151
(9.1, 10.0]                 22.802226    620

In [32]:
df.to_csv(
    "../Data/cleaned_ai_student.csv",
    index=False
)